Repository HITK-TECH-Community/Community-Website, pull requests merged in 2020-12, with the labels that each got.

#72 backend-setup
  .gitignore
  backend/.eslintrc.json
  backend/.gitignore
  backend/.prettierrc
  backend/Adminauthenticate.js
  backend/app.js
  backend/app/models/Admin.js
  backend/app/routes/admin/@validationSchema/index.js
  backend/app/routes/admin/createSuperAdmin.js
  backend/app/routes/admin/index.js
  backend/app/routes/admin/postSuperAdmin.js
  backend/app/routes/auth/@validationSchema/index.js
  backend/app/routes/auth/index.js
  backend/app/routes/auth/login.js
  backend/app/routes/index.js
  backend/bin/www
  backend/config.js
  backend/config/index.js
  backend/config/variables.json
  backend/constants/constants.json
  backend/constants/index.js
  backend/helpers/dbConnection.js
  backend/helpers/error.js
  backend/helpers/middlewares/auth.js
  backend/helpers/middlewares/validation.js
  backend/helpers/utils.js
  backend/index.js
  backend/models/Adminuser.js
  backend/package-lock.json
  backend/package.json
  backend/public/stylesheets/style.css
  backend/routes/Adminusers.js
  backend/routes/cors.js
  backend/routes/index.js
  backend/views/error.jade
  backend/views/index.jade
  backend/views/layout.jade
Labels: backend

#113 logo added
  assets/logo/Himanshu.gif
Labels: DWOC, Level-4

#115 Added Admin UI Assets
  assets/Admin_page_assets/Nav-icons/mdi_announcement.svg
  assets/Admin_page_assets/Nav-icons/mdi_donut_small.svg
  assets/Admin_page_assets/Nav-icons/mdi_equalizer.svg
  assets/Admin_page_assets/Nav-icons/mdi_home.svg
  assets/Admin_page_assets/Nav-icons/mdi_settings.svg
  assets/Admin_page_assets/Viewers-icons/Ellipse 1.svg
  assets/Admin_page_assets/Viewers-icons/mdi_more_vert.svg
  assets/Admin_page_assets/graph.svg
  assets/Admin_page_assets/undraw_Designer_by46.svg
Labels: DWOC, Level-4

#130 Issue #100 resolved
  frontend/src/components/navbar/navbar.css
Labels: DWOC, Level-3

#124 Adding links for About Us UI design
  assets/About us/aboutus.md
Labels: DWOC, Level-4

#134 Adding Broadcast UI
  assets/Broadcast_page/kanishka.md
Labels: DWOC, Level-4

#132 implemented resource sharing page for DWoC
  frontend/public/images/resource.png
  frontend/src/components/resource/resources.css
  frontend/src/components/resource/resources.js
Labels: DWOC, Level-4

#133 Modified design of FAQ and created separate file for inline css
  frontend/public/images/faq.jpg
  frontend/src/components/faq/faqs.css
  frontend/src/components/faq/faqs.js
  frontend/src/components/home/motive/motive.css
Labels: DWOC, Level-3

#137 AboutUsPage UI #9 DWOC
  assets/About us page/SHIVANI WAKDE/About US 1.png
  assets/About us page/SHIVANI WAKDE/About Us 2.png
Labels: DWOC, Level-4

#142 Final footer changes
  frontend/src/components/footer/footer.css
  frontend/src/components/footer/footer.js
Labels: DWOC, Level-3
