Repository HITK-TECH-Community/Community-Website, pull requests merged in 2021-04, with the labels that each got.

#581 arrow stylings changed
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/components/Carousel/Carousel.jsx
  frontend/src/pages/Home/components/Carousel/owl-carousel-styles.css
  frontend/src/pages/Home/nav-icon.png
Labels: Level2, gssoc21

#585 Added dark theme to the Login Section and Forgot Password Section
  frontend/src/app.js
  frontend/src/pages/ForgotPassword/ForgotPassword.jsx
  frontend/src/pages/ForgotPassword/ForgotPassword.module.scss
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Login/login.module.scss
Labels: Level3, gssoc21

#591 Updated Code Structure to the Conventions File
  frontend/conventions.md
Labels: Level1, gssoc21

#587 Refactored footer and changed logo on navbar in dark mode
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/footer.module.scss
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Navbar/navbar.module.scss
Labels: Level2, gssoc21

#590 Revamped the broadcast section
  frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
  frontend/src/pages/Broadcast/Component/Carousel/carousel.module.scss
Labels: Level2, gssoc21

#597 loader added in manage admin
  frontend/src/components/util/Loader/index.js
  frontend/src/pages/Admin/Components/Setting/Manage/Manage.jsx
Labels: Level2, gssoc21

#594 Clickable card in Admin Dashboard Settings
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Setting/Setting.jsx
  frontend/src/pages/Admin/Components/Setting/setting.module.scss
Labels: Level2, gssoc21

#603 Admin-LoginPage Responsive Issue Fixed
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Login/login.module.scss
Labels: Level2, gssoc21

#606 Refactored admin dashboard cards
  frontend/src/pages/Admin/Components/Dashboard/Dashboard.jsx
  frontend/src/pages/Admin/Components/Dashboard/dashboard.module.scss
Labels: Level2, gssoc21

#609 Fixed Responsive Issues & Syntax-Warnings
  frontend/src/pages/ForgotPassword/ForgotPassword.jsx
  frontend/src/pages/ForgotPassword/ForgotPassword.module.scss
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/ResourceSharingForm.jsx
Labels: Level2, gssoc21

#611 `Open Source Contributors` section added in About us page
  frontend/src/pages/About/About.jsx
  frontend/src/pages/About/about.module.scss
Labels: Level2, gssoc21

#612 Adding route for FAQ
  backend/app/models/faq.js
  backend/app/routes/faq/@validationSchema/index.js
  backend/app/routes/faq/index.js
  backend/app/routes/faq/post.js
  backend/app/routes/index.js
  backend/docs/FAQ.md
  backend/docs/images/addFAQ.JPG
  backend/package.json
  backend/tests/routes/FAQ/POST_FAQ.test.js
  package-lock.json
Labels: backend

#621 Styled Scroll top button
  frontend/src/app.js
  frontend/src/components/util/ScrollToTop/ScrollToTop.jsx
  frontend/src/components/util/ScrollToTop/scroll-to-top.module.scss
Labels: Level2, gssoc21

#620 Enhancement in Join Us section
  frontend/src/pages/Home/components/JoinUs/join-us.module.scss
Labels: Level2, gssoc21

#624 Admin card UI changed
  frontend/src/pages/Admin/Components/Profile/Profile.jsx
  frontend/src/pages/Admin/Components/Profile/profile.module.scss
Labels: Level2, gssoc21

#626 Contributors-Img Section made responsive
  frontend/src/pages/About/About.jsx
  frontend/src/pages/About/about.module.scss
Labels: Level2, gssoc21

#622 styled dashboard
  frontend/src/pages/Admin/Components/Dashboard/dashboard.module.scss
  frontend/src/pages/Admin/Components/Setting/setting.module.scss
  frontend/src/pages/Admin/admin.module.scss
Labels: Level3, gssoc21

#631 Issue #630 Fixed
  frontend/src/pages/About/About.jsx
  frontend/src/pages/About/about.module.scss
Labels: Level2, gssoc21
