Repository HITK-TECH-Community/Community-Website, pull requests merged in 2021-12, with the labels that each got.

#669 Fixess #667 - Broadcast Page Error
  frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
Labels: Swoc

#675 670
  frontend/src/components/util/Loader/index.js
  frontend/src/pages/Broadcast/Component/AllBroadcasts/AllBroadcasts.jsx
  frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
Labels: Level2, Swoc

#673 Delete and Get FAQ endpoints added
  backend/app/routes/faq/DeleteFaq.js
  backend/app/routes/faq/GetFaq.js
  backend/app/routes/faq/index.js
  backend/app/routes/index.js
  frontend/package-lock.json
  frontend/yarn.lock
  package-lock.json
Labels: Level3, Swoc
