Repository HITK-TECH-Community/Community-Website, pull requests merged in 2021-05, with the labels that each got.

#632 Admin-panel cards
  frontend/src/pages/Admin/Components/About/about-us.module.scss
  frontend/src/pages/Admin/Components/Broadcast/broadcast.module.scss
  frontend/src/pages/Admin/Components/Faq/faq.module.scss
Labels: Level2, gssoc21

#629 Join us form validation
  frontend/src/pages/Home/components/JoinUsForm/Form.jsx
  frontend/src/pages/Home/components/JoinUsForm/form.module.scss
Labels: Level2, gssoc21

#637 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Level0, gssoc21

#633 added scrollbar in broadcasts
  frontend/src/pages/Broadcast/Component/Carousel/Modal/modals.module.scss
Labels: Level2, gssoc21

#636 Issue #634 Fixed
  frontend/src/components/Navbar/navbar.module.scss
Labels: Level2, gssoc21

#618 Get Broadcasts #497
  backend/app/routes/broadcast/@validationSchema/index.js
  backend/app/routes/broadcast/getBroadcasts.js
  backend/app/routes/broadcast/index.js
  backend/app/routes/index.js
  backend/constants/constants.json
  backend/docs/broadcast.md
  backend/tests/routes/broadcast/getBroadcasts.test.js
Labels: backend, gssoc21

#649 Join us form dark theme of domain input field
  frontend/src/pages/Home/components/JoinUsForm/form.module.scss
Labels: Level2, gssoc21

#657 Updated README
  README.md
Labels: Level0, gssoc21
