Repository HITK-TECH-Community/Community-Website, pull requests merged in 2021-02, with the labels that each got.

#310 Reduce the button size
  frontend/src/components/auth/login/login.css
  frontend/src/components/resource/resources.css
  frontend/src/components/terms/terms.css
  frontend/src/components/terms/terms.js
Labels: Level-3, SWOC

#322 Join us page for DWoC
  frontend/.gitignore
  frontend/public/images/joinus.jpg
  frontend/src/app.js
  frontend/src/components/home/home.js
  frontend/src/components/home/join_us/join_us.css
  frontend/src/components/home/join_us/join_us.js
  frontend/src/components/home/join_us/join_us_form/form.css
  frontend/src/components/home/join_us/join_us_form/form.js
Labels: DWOC, Level-4

#325 Logo
  assets/logo/community-logo.jpg
Labels: DWOC, Level-4

#326 Uploaded the new logo for website
  assets/logo/logo.png
Labels: DWOC, Level-4

#329 borderCorner of the footer icons R now rounded🤩🤩
  frontend/src/components/footer/footer.css
  frontend/src/components/footer/footer.js
Labels: DWOC, Level-3, SWOC

#332 Updated CONTRIBUTING.md with images
  CONTRIBUTING.md
  assets/cont-img/addFile.png
  assets/cont-img/br.png
  assets/cont-img/commit.png
  assets/cont-img/compare.png
  assets/cont-img/createBr.png
  assets/cont-img/fork.png
  assets/cont-img/issue.png
  assets/cont-img/pr.png
  assets/cont-img/prTemp.png
Labels: DWOC, Level-3

#333 removed the black border after clicking on join us button
  frontend/src/components/footer/footer.css
  frontend/src/components/home/join_us/join_us.css
  frontend/src/components/util/button/button.css
Labels: Level-3

#334 Admin
  frontend/src/app.js
  frontend/src/components/admin/admin.css
  frontend/src/components/admin/admin.js
  frontend/src/components/admin/broadcast/broadcast.js
  frontend/src/components/admin/contact/contact.js
  frontend/src/components/admin/dashboard/dashboard.css
  frontend/src/components/admin/dashboard/dashboard.js
  frontend/src/components/admin/faq/faq.js
  frontend/src/components/admin/profile/profile.css
  frontend/src/components/admin/profile/profile.jsx
Labels: Level-4, SWOC

#345 changed the size of footer icons
  frontend/src/components/footer/footer.css
  frontend/src/components/footer/footer.js
Labels: DWOC, Level-3

#346 View broadcasts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.css
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.js
  frontend/src/components/broadcast/all_broadcasts/card/card.css
  frontend/src/components/broadcast/all_broadcasts/card/card.js
Labels: DWOC, Level-4, SWOC

#350 community logo added for DWoC
  frontend/public/index.html
  frontend/src/components/navbar/navbar.css
  frontend/src/components/navbar/navbar.js
Labels: DWOC, Level-3

#351 FAQ Page Bug
  frontend/src/components/faq/faq.css
  frontend/src/components/faq/faq.js
Labels: Level-4, SWOC

#352 Applying module.css
  frontend/package.json
  frontend/src/components/admin/about/about.jsx
  frontend/src/components/admin/admin.js
  frontend/src/components/admin/admin.module.css
  frontend/src/components/admin/broadcast/broadcast.js
  frontend/src/components/admin/contact/contact.js
  frontend/src/components/admin/dashboard/dashboard.js
  frontend/src/components/admin/dashboard/dashboard.module.css
  frontend/src/components/admin/faq/faq.js
  frontend/src/components/admin/profile/profile.jsx
  frontend/src/components/admin/profile/profile.module.css
  frontend/src/components/admin/setting/setting.js
  frontend/src/components/admin/setting/setting.module.css
Labels: Level-4, SWOC

#359 converted css to css modules section6
  frontend/src/components/home/join_us/join_us.js
  frontend/src/components/home/join_us/join_us.module.css
  frontend/src/components/home/join_us/join_us_form/form.js
  frontend/src/components/home/join_us/join_us_form/form.module.css
Labels: DWOC, Level-4, SWOC

#363 Converted css files to css modules - section 8
  frontend/src/components/resource/resources.js
  frontend/src/components/resource/resources.module.css
  frontend/src/components/terms/terms.js
  frontend/src/components/terms/terms.module.css
Labels: DWOC, Level-4, SWOC

#358 converted css to css modules: section2
  frontend/src/components/404/not_found.js
  frontend/src/components/404/not_found.module.css
  frontend/src/components/about/about_us.css
  frontend/src/components/about/about_us.js
  frontend/src/components/about/about_us.module.css
  frontend/src/components/auth/login/login.js
  frontend/src/components/auth/login/login.module.css
  frontend/src/components/contact/contact_us.js
  frontend/src/components/contact/contact_us.module.css
  frontend/src/components/home/join_us/join_us.js
  frontend/src/components/util/button/button.css
  frontend/src/components/util/button/button.js
Labels: DWOC, Level-4, SWOC

#361 modified newsletter
  frontend/src/components/footer/footer.css
  frontend/src/components/footer/footer.js
Labels: DWOC, Level-3

#367 Enhancement in Setting
  frontend/src/components/admin/admin.js
  frontend/src/components/admin/setting/Invite/Invite.js
  frontend/src/components/admin/setting/Invite/Invite.module.css
  frontend/src/components/admin/setting/Manage/Manage.js
  frontend/src/components/admin/setting/Manage/Manage.module.css
  frontend/src/components/admin/setting/setting.js
  frontend/src/components/admin/setting/setting.module.css
Labels: Level-4, SWOC

#364 Converted css files to css modules - section 4
  frontend/src/components/broadcast/Carousel/Carousel.js
  frontend/src/components/faq/faq.js
  frontend/src/components/faq/faq.module.css
  frontend/src/components/footer/footer.js
  frontend/src/components/footer/footer.module.css
  frontend/src/components/home/carousel/carousel.js
  frontend/src/components/home/home.js
  frontend/src/components/home/home.module.css
  frontend/src/components/home/join_us/join_us.js
  frontend/src/components/home/motive/motive.js
  frontend/src/components/home/motive/motive.module.css
  frontend/src/components/home/overview/overview.js
  frontend/src/components/home/overview/overview.module.css
Labels: DWOC, Level-4, SWOC

#366 Broadcast Page for Admin
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.js
  frontend/src/components/admin/add_broadcasts/add_broadcasts.js
  frontend/src/components/admin/add_broadcasts/add_broadcasts.module.css
  frontend/src/components/admin/broadcast/broadcast.js
  frontend/src/components/admin/broadcast/broadcast.module.css
Labels: DWOC, Level-4, SWOC

#368 Broadcast
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.css
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.js
  frontend/src/components/dropmenu/DropMenu.jsx
Labels: DWOC, Level-3

#323 Backend Documentation (Admin module)
  backend/docs/admin.md
  backend/docs/images/basic.jpg
  backend/docs/images/error.jpg
  backend/docs/images/jwt.jpg
  backend/docs/images/loginroute.jpg
  backend/docs/images/passwordchange.jpg
  backend/docs/images/postsuperadmin.jpg
Labels: Level-2, backend

#379 [Fix] password field
  frontend/public/index.html
  frontend/src/components/auth/login/login.js
  frontend/src/components/dropmenu/DropMenu.jsx
  frontend/src/components/home/join_us/join_us_form/form.js
  frontend/src/components/home/join_us/join_us_form/form.module.css
  frontend/src/components/navbar/navbar.css
  frontend/src/components/navbar/navbar.js
Labels: DWOC, Level-3, SWOC

#382 Refactored Broadcasts
  frontend/src/components/broadcast/Carousel/Carousel.js
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.js
  frontend/src/components/broadcast/all_broadcasts/card/card.js
  frontend/src/test_data/broadcast_text.json
Labels: DWOC, Level-5, SWOC

#380 Proposal for refactoring the project
  frontend/PROPOSAL.md
Labels: documentation

#393 buttons fixed
  frontend/src/components/auth/login/login.js
  frontend/src/components/auth/login/login.module.css
  frontend/src/components/contact/contact_us.js
  frontend/src/components/contact/contact_us.module.css
  frontend/src/components/home/join_us/join_us_form/form.module.css
Labels: DWOC, Level-3

#392 Broadcast
  frontend/src/components/broadcast/Carousel/Carousel.js
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.css
  frontend/src/components/get_involved/get_involved.css
  frontend/src/components/get_involved/get_involved.js
Labels: DWOC, Level-3

#390 Fixed Dashboard
  frontend/src/components/admin/admin.js
  frontend/src/components/admin/admin.module.css
  frontend/src/components/admin/dashboard/dashboard.js
  frontend/src/components/admin/dashboard/dashboard.module.css
  frontend/src/components/admin/profile/profile.module.css
  frontend/src/components/admin/setting/setting.js
Labels: DWOC, Level-3

#394 Edit Broadcast
  frontend/src/components/broadcast/Carousel/Carousel.css
  frontend/src/components/broadcast/Carousel/Carousel.js
  frontend/src/components/broadcast/Carousel/Edit/Edit.jsx
  frontend/src/components/broadcast/Carousel/Edit/Edit.module.scss
  frontend/src/components/broadcast/all_broadcasts/Edit/Edit.jsx
  frontend/src/components/broadcast/all_broadcasts/Edit/Edit.module.scss
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.js
  frontend/src/components/broadcast/all_broadcasts/card/card.css
  frontend/src/components/broadcast/all_broadcasts/card/card.js
  frontend/src/test_data/broadcast_text.json
Labels: Level-4, SWOC

#398 Added GitHub action to auto assign mentor
  .github/auto_assign.yml
  .github/workflows/action.yml
Labels: DWOC, Level-4

#395 carousel css converted to carousel.module.css
  frontend/src/components/broadcast/Carousel/Carousel.js
  frontend/src/components/broadcast/Carousel/Carousel.module.css
  frontend/src/components/broadcast/Carousel/customOwlCarouselStyle.css
Labels: DWOC, Level-3, SWOC

#404 Broadcast admin frontend
  frontend/src/components/admin/broadcast/broadcast.js
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.css
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.js
  frontend/src/components/broadcast/all_broadcasts/card/card.css
  frontend/src/components/broadcast/all_broadcasts/card/card.js
Labels: DWOC, Level-4, SWOC

#324 Url shortener
  backend/app/models/tinyURL.js
  backend/app/routes/admin/changePassword.js
  backend/app/routes/index.js
  backend/app/routes/tinyURL/@validationSchema/index.js
  backend/app/routes/tinyURL/API Tests.postman_collection.json
  backend/app/routes/tinyURL/index.js
  backend/app/routes/tinyURL/redirectURL.js
  backend/app/routes/tinyURL/shortenURL.js
  backend/config/variables.json
  backend/package-lock.json
  backend/package.json
Labels: DWOC, Level-4, SWOC, backend

#405 Enhancement in Edit broadcast modal
  frontend/src/components/broadcast/all_broadcasts/Edit/Edit.jsx
  frontend/src/components/broadcast/all_broadcasts/Edit/Edit.module.scss
  frontend/src/components/home/carousel/carousel.css
Labels: Level-3, SWOC

#420 Enhancement in Add Broadcast Page of Admin
  frontend/src/app.js
  frontend/src/components/admin/add_broadcasts/add_broadcasts.js
  frontend/src/components/admin/broadcast/add_broadcasts/add_broadcasts.js
  frontend/src/components/admin/broadcast/add_broadcasts/add_broadcasts.module.css
Labels: DWOC, Level-4, SWOC

#431 Fixed font-size
  frontend/src/components/auth/login/login.module.css
  frontend/src/components/contact/contact_us.module.css
  frontend/src/components/footer/footer.module.css
  frontend/src/components/home/join_us/join_us_form/form.module.css
  frontend/src/components/resource/resources.module.css
Labels: DWOC, Level-3

#436 Issue Template Updates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/component_refactor.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: DWOC, Level-2

#426 Sass for util components and terms page
  frontend/src/app.js
  frontend/src/components/auth/login/login.js
  frontend/src/components/contact/contact_us.js
  frontend/src/components/home/join_us/join_us.js
  frontend/src/components/home/join_us/join_us_form/form.js
  frontend/src/components/resource/resources.js
  frontend/src/components/util/Button/Button.jsx
  frontend/src/components/util/Button/button.module.scss
  frontend/src/components/util/Button/index.js
  frontend/src/components/util/Dropdown/Dropdown.jsx
  frontend/src/components/util/Dropdown/MenuItems.js
  frontend/src/components/util/Dropdown/dropdown.module.scss
  frontend/src/components/util/Dropdown/index.js
  frontend/src/components/util/ScrollToTop/ScrollToTop.jsx
  frontend/src/components/util/ScrollToTop/index.js
  frontend/src/components/util/ScrollToTop/scroll-to-top.module.scss
  frontend/src/pages/404/NotFound.jsx
  frontend/src/pages/Admin/Components/Broadcast/AddBroadcasts/AddBroadcasts.jsx
  frontend/src/pages/Admin/Components/Faq/AddFaq/AddFaq.jsx
  frontend/src/pages/Terms/Terms.jsx
  frontend/src/pages/Terms/index.js
  frontend/src/pages/Terms/terms.module.css
Labels: DWOC, Level-5, SWOC

#437 section3 done (css to css modules conversion)
  frontend/src/components/broadcast/Carousel/Modal/Modals.js
  frontend/src/components/broadcast/Carousel/Modal/modal.module.css
  frontend/src/components/broadcast/all_broadcasts/all-broadcasts.module.css
  frontend/src/components/broadcast/all_broadcasts/all_broadcasts.js
  frontend/src/components/broadcast/broadcast.module.css
  frontend/src/components/broadcast/broadcasts.js
Labels: DWOC, Level-4, SWOC

#438 Refactoring Login & ContactUs components
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.js
  frontend/src/pages/ContactUs/ContactUs.jsx
  frontend/src/pages/ContactUs/ContactUs.module.scss
  frontend/src/pages/ContactUs/index.js
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/login.module.scss
  frontend/src/pages/Terms/Terms.jsx
Labels: DWOC, Level-4

#443 Refactored broadcast component
  frontend/src/app.js
  frontend/src/pages/Broadcast/Broadcast.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/AllBroadcasts.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Card/Card.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Card/card.module.scss
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Card/index.js
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Edit/Edit.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Edit/edit.module.scss
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Edit/index.js
  frontend/src/pages/Broadcast/Component/AllBroadcasts/all-broadcasts.module.scss
  frontend/src/pages/Broadcast/Component/AllBroadcasts/index.js
  frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
  frontend/src/pages/Broadcast/Component/Carousel/Edit/Edit.jsx
  frontend/src/pages/Broadcast/Component/Carousel/Edit/edit.module.scss
  frontend/src/pages/Broadcast/Component/Carousel/Edit/index.js
  frontend/src/pages/Broadcast/Component/Carousel/Modal/Modals.jsx
  frontend/src/pages/Broadcast/Component/Carousel/Modal/index.js
  frontend/src/pages/Broadcast/Component/Carousel/Modal/modals.module.scss
  frontend/src/pages/Broadcast/Component/Carousel/carousel.module.scss
  frontend/src/pages/Broadcast/Component/Carousel/custom-owl-carousel-style.scss
  frontend/src/pages/Broadcast/Component/Carousel/index.js
  frontend/src/pages/Broadcast/broadcast.module.scss
  frontend/src/pages/Broadcast/index.js
Labels: DWOC, Level-4, SWOC

#447 nav for mobile view fixed
  frontend/src/components/Navbar/Navbar.jsx
Labels: DWOC, Level-3, SWOC

#450 Removing redundant styles from different components
  frontend/src/pages/404/not-found.module.scss
  frontend/src/pages/About/about.module.scss
  frontend/src/pages/Admin/Components/Broadcast/broadcast.module.scss
  frontend/src/pages/Admin/Components/Dashboard/dashboard.module.scss
  frontend/src/pages/Broadcast/Component/AllBroadcasts/all-broadcasts.module.scss
  frontend/src/pages/Broadcast/broadcast.module.scss
  frontend/src/pages/PrivacyPolicy/privacy-policy.module.scss
Labels: DWOC, Level-3, SWOC

#452 Refactored Invite and Manage component
  frontend/src/pages/Admin/Components/Setting/Invite/Invite.jsx
  frontend/src/pages/Admin/Components/Setting/Invite/Invite.module.scss
  frontend/src/pages/Admin/Components/Setting/Manage/Manage.jsx
Labels: DWOC, Level-3, SWOC

#455 Home Top Section Responsiveness
  frontend/src/pages/Home/components/Overview/overview.module.scss
Labels: DWOC, Level-3

#458 added toast
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/util/Toast/Toast.jsx
  frontend/src/components/util/Toast/index.js
  frontend/src/components/util/Toast/toast.module.scss
Labels: DWOC, Level-4, SWOC

#464 Implement the Auth guard in dashboard
  frontend/src/app.js
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/store/actions/auth.js
  frontend/src/store/reducers/reducer.js
Labels: Level-4, SWOC

#466 Icon only visible to super admin
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Card/Card.jsx
Labels: Level-3, SWOC

#470 Add toast after logout
  frontend/src/pages/Login/Login.jsx
  frontend/src/store/actions/auth.js
  frontend/src/store/reducers/reducer.js
Labels: Level-3, SWOC
