Repository HITK-TECH-Community/Community-Website, pull requests merged in 2021-03, with the labels that each got.

#508 Refresh Issue Solved
  frontend/public/_redirects
Labels: Level2, gssoc21

#509 About us
  frontend/package.json
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/About/About.jsx
  frontend/src/pages/Admin/Components/About/about-us.module.scss
  frontend/src/pages/Admin/Components/AddTeamMember/AddTeamMember.jsx
  frontend/src/pages/Admin/Components/AddTeamMember/add-team-member.module.scss
  frontend/src/pages/Admin/Components/AddTeamMember/index.js
  frontend/src/pages/Admin/Components/MangeTeams/ManageTeams.jsx
  frontend/src/pages/Admin/Components/MangeTeams/index.js
  frontend/src/pages/Admin/Components/MangeTeams/manage-teams.module.scss
  frontend/src/test_data/teams.js
  frontend/yarn.lock
Labels: Level3, gssoc21

#514 auto-hide timer added (set to 3seconds)
  frontend/package-lock.json
  frontend/src/components/util/Toast/Toast.jsx
  frontend/src/pages/Login/Login.jsx
Labels: Level2, gssoc21

#518 gssoc badge added to readme.md file
  README.md
  assets/GSSoC.png
Labels: Level0, gssoc21

#519 enhancement in code structure
  frontend/src/components/Footer/Footer.jsx
  frontend/src/pages/Home/components/JoinUs/JoinUs.jsx
  frontend/src/pages/Home/components/Motive/Motive.jsx
  frontend/src/pages/Terms/Terms.jsx
Labels: Level2, gssoc21

#520 Dash fixed for smaller screens in All Broadcasts page
  frontend/src/pages/Broadcast/Component/AllBroadcasts/AllBroadcasts.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/all-broadcasts.module.scss
Labels: Level2, gssoc21

#533 Adding Validation resource form
  frontend/package.json
  frontend/src/pages/Resources/components/ResourceSharingForm/ResourceSharingForm.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/resource-sharing-form.module.scss
Labels: Level2, gssoc21

#542 Added dark theme to the Resources page and contact section
  frontend/package-lock.json
  frontend/src/app.js
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/util/Toggle/Toggle.jsx
  frontend/src/components/util/Toggle/toggle.module.scss
  frontend/src/pages/ContactUs/ContactUs.jsx
  frontend/src/pages/ContactUs/ContactUs.module.scss
  frontend/src/pages/Resources/Resources.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/ResourceSharingForm.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/resource-sharing-form.module.scss
  frontend/src/pages/Resources/resources.module.scss
Labels: Level2, gssoc21

#525 feat(forgot-password-recovery-page): Add forgot password recovery page(#502)
  frontend/package-lock.json
  frontend/public/images/forgot-password-recovery.jpg
  frontend/src/app.js
  frontend/src/pages/ForgotPasswordRecovery/ForgotPasswordRecovery.jsx
  frontend/src/pages/ForgotPasswordRecovery/ForgotPasswordRecovery.module.scss
  frontend/src/pages/ForgotPasswordRecovery/index.js
  frontend/src/test_data/superadmin_credential.json
Labels: Level3, gssoc21

#545 Login form validaion added(#537)
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Login/login.module.scss
Labels: Level2, gssoc21

#544 Refactored all broadcasts page
  frontend/src/components/util/DropMenu/DropMenu.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/AllBroadcasts.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Card/Card.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Card/card.module.scss
  frontend/src/pages/Broadcast/Component/AllBroadcasts/all-broadcasts.module.scss
Labels: Level3, gssoc21

#552 [Frontend] Make the FAQ and About Us card Consistent
  frontend/src/pages/Admin/Components/About/About.jsx
  frontend/src/pages/Admin/Components/About/about-us.module.scss
  frontend/src/pages/Admin/Components/Broadcast/broadcast.module.scss
  frontend/src/pages/Admin/Components/Faq/faq.module.scss
Labels: Level2, gssoc21

#548 Updated Validations & Card UI
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/footer.module.scss
  frontend/src/pages/ContactUs/ContactUs.jsx
  frontend/src/pages/ContactUs/ContactUs.module.scss
Labels: Level3, gssoc21

#550 As the jwt token expires, remove it from local storage
  frontend/package.json
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/store/reducers/reducer.js
Labels: Level3, gssoc21

#556 Collapsible menu for small screen added in admin page
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/admin.module.scss
Labels: Level3, frontend

#559 Refactored terms of use, Privacy Policy and Get Involved pages
  frontend/src/pages/GetInvolved/get-involved.module.scss
  frontend/src/pages/PrivacyPolicy/privacy-policy.module.scss
  frontend/src/pages/Terms/terms.module.css
Labels: Level2, gssoc21

#560 Added Dark Theme to the FAQ and Join Us Pages, modified few images and made the toggle responsive.
  frontend/public/images/FAQ2.png
  frontend/public/images/joinus2.png
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Navbar/navbar.module.scss
  frontend/src/components/util/Toggle/Toggle.jsx
  frontend/src/pages/Faq/Faq.jsx
  frontend/src/pages/Faq/faq.module.scss
  frontend/src/pages/Home/components/JoinUsForm/Form.jsx
  frontend/src/pages/Home/components/JoinUsForm/form.module.scss
Labels: Level3, gssoc21

#561 Added Card-Message for news-letter
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/footer.module.scss
Labels: Level2, gssoc21

#540 Enhancement in forms
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/app.css
  frontend/src/pages/ContactUs/ContactUs.jsx
  frontend/src/pages/ContactUs/ContactUs.module.scss
  frontend/src/pages/ForgotPassword/ForgotPassword.jsx
  frontend/src/pages/ForgotPassword/ForgotPassword.module.scss
Labels: Level3, gssoc21

#563 Fixed checkbox of join us form for small screen(#562)
  frontend/src/pages/Home/components/JoinUsForm/form.module.scss
Labels: Level2, gssoc21

#577 Added dark mode to 404 page and terms of use page
  frontend/public/images/error.png
  frontend/src/components/ErrorHandlerPages/404/NotFound.jsx
  frontend/src/components/ErrorHandlerPages/404/not-found.module.scss
  frontend/src/pages/Terms/Terms.jsx
  frontend/src/pages/Terms/terms.module.css
Labels: Level3, gssoc21

#573 Added dark-theme to Footer
  frontend/src/app.js
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/footer.module.scss
Labels: Level2, gssoc21

#567 Success card on password change
  frontend/src/pages/Admin/Components/Setting/ResetPassword/ResetPassword.jsx
  frontend/src/pages/Admin/Components/Setting/ResetPassword/reset-password.module.scss
Labels: Level2, gssoc21

#578 Added dark mode to navbar
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Navbar/navbar.module.scss
Labels: Level3, gssoc21

#571 Added dark mode to get involved and privacy policy pages
  frontend/src/pages/GetInvolved/GetInvolved.jsx
  frontend/src/pages/GetInvolved/get-involved.module.scss
  frontend/src/pages/PrivacyPolicy/PrivacyPolicy.jsx
  frontend/src/pages/PrivacyPolicy/privacy-policy.module.scss
Labels: Level3, gssoc21

#579 Remove extra warnings and fix invite form validation
  frontend/src/pages/Admin/Components/Setting/Invite/Invite.jsx
  frontend/src/pages/ContactUs/ContactUs.jsx
  frontend/src/pages/ForgotPassword/ForgotPassword.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/ResourceSharingForm.jsx
Labels: Level2, gssoc21
