Repository HITK-TECH-Community/Community-Website, pull requests merged in 2021-01, with the labels that each got.

#157 Modified Login Page
  frontend/public/images/login-illustration.png
  frontend/src/components/admin/admin.js
  frontend/src/components/auth/login/login.css
  frontend/src/components/auth/login/login.js
Labels: DWOC, Level-4

#151 BroadcastPageUi added #6 DWOC
  assets/Broadcast_page/SHIVANI WAKDE/BroadcastPage1 (1).png
  assets/Broadcast_page/SHIVANI WAKDE/BroadcastPage1 (2).png
Labels: DWOC, Level-4

#155 Added Welcome Bot config file
  .github/config.yml
Labels: DWOC, Level-2

#149 ResourceSharingUi added #11 DWOC
  assets/Resource_Sharing_Form_UI/SHIVANI WAKDE/ResourcePage1.png
  assets/Resource_Sharing_Form_UI/SHIVANI WAKDE/ResourcePage2.png
  assets/Resource_Sharing_Form_UI/SHIVANI WAKDE/image.png
  assets/Resource_Sharing_Form_UI/SHIVANI WAKDE/resource sharing page.png
Labels: DWOC, Level-4

#166 Fixed carousel section
  frontend/src/components/home/carousel/carousel.css
  frontend/src/components/home/carousel/carousel.js
Labels: DWOC, Level-3

#159 1)Removed unwanted hover effects from card in about section. 2)Added …
  frontend/src/components/about/about_us.css
  frontend/src/components/about/about_us.js
  frontend/src/components/footer/footer.css
  frontend/src/components/footer/footer.js
Labels: DWOC, Level-3

#168 Made navbar such that it will be able to contain more tabs
  frontend/src/components/navbar/navbar.css
Labels: DWOC, Level-3

#176 implemented terms of use page for DWoC #163
  frontend/public/images/terms.png
  frontend/src/app.js
  frontend/src/components/footer/footer.js
  frontend/src/components/terms/terms.css
  frontend/src/components/terms/terms.js
Labels: DWOC, Level-4

#186 Replace class with className #178
  frontend/src/components/terms/terms.js
Labels: DWOC, Level-3, SWOC

#190 Fix the design of FAQ page
  frontend/src/components/faq/faq.png
  frontend/src/components/faq/faqs.css
  frontend/src/components/faq/faqs.js
Labels: Level-3, SWOC

#189 Updating issue templates
  .github/issue_template/bug_report.md
  .github/issue_template/feature_request.md
Labels: Level-2, SWOC

#212 new home page ui design added
  assets/Home Page/yashsehgal/homepage.png
Labels: DWOC, Level-3

#209 new page ui design for about us section added
  assets/About us page/yashsehgal/about-us-page.png
Labels: DWOC, Level-4

#207 website logo for DWoC #85
  assets/logo/vedika.png
Labels: DWOC, Level-4

#202 Adding Broadcast page UI Designs
  assets/Broadcast_page/README.md
  assets/Broadcast_page/SHITIZ AGGARWAL/Design-1a.png
  assets/Broadcast_page/SHITIZ AGGARWAL/Design-1b.png
  assets/Broadcast_page/SHITIZ AGGARWAL/Design-2.png
Labels: Level-4, SWOC

#205 Made privacy policy page
  frontend/public/images/privacy-policy-image.png
  frontend/src/app.js
  frontend/src/components/footer/footer.js
  frontend/src/components/privacy-policy/privacy-policy.css
  frontend/src/components/privacy-policy/privacy-policy.js
Labels: DWOC, Level-4

#204 Added prettier as pre-commit hook
  frontend/.prettierignore
  frontend/package-lock.json
  frontend/package.json
Labels: DWOC, Level-4

#218 new admin page ui design added
  assets/Admin_page_assets/yashsehgal/admin-page.png
Labels: DWOC, Level-4

#217 broadcasts page ui design added
  assets/Broadcast_page/yashsehgal/broadcasts-page-ui.png
Labels: DWOC, Level-4

#199 Enhancement in Resource sharing page #171
  frontend/debug.log
  frontend/src/components/resource/resources.css
  frontend/src/components/resource/resources.js
  frontend/src/components/util/button/button.css
Labels: DWOC, Level-3

#211 fix for #164
  frontend/src/app.js
  frontend/src/components/footer/footer.js
  frontend/src/components/involvement/get_involved.css
  frontend/src/components/involvement/get_involved.js
Labels: DWOC, Level-4

#200 Login page
  frontend/src/components/auth/loginPage-VaishnaviShah/login.css
  frontend/src/components/auth/loginPage-VaishnaviShah/login.js
  frontend/src/components/auth/loginPage-VaishnaviShah/student-login.png
Labels: DWOC, Level-4

#220 faq section change
  frontend/src/components/faq/faq.css
  frontend/src/components/faq/faq.js
Labels: DWOC, Level-3

#188 Login Page Enhancement
  frontend/public/index.html
  frontend/src/components/auth/login/login.css
  frontend/src/components/auth/login/login.js
  frontend/src/components/contact/contact_us.css
Labels: Level-5, SWOC

#228 contact us page enhancement #221 for DWoC
  frontend/src/components/contact/contact_us.css
  frontend/src/components/contact/contact_us.js
Labels: DWOC, Level-3

#206 Broadcast Page Design
  frontend/src/components/broadcast/Carousel/Carousel.css
  frontend/src/components/broadcast/Carousel/Carousel.js
  frontend/src/components/broadcast/Carousel/Modal/Modal.css
  frontend/src/components/broadcast/Carousel/Modal/Modals.js
  frontend/src/components/broadcast/broadcast.css
  frontend/src/components/broadcast/broadcasts.js
Labels: Level-5, SWOC

#236 Issue template bug
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: DWOC, Level-1

#237 Resources UI
  frontend/src/components/resource/resources.css
  frontend/src/components/resource/resources.js
  frontend/src/components/util/button/button.css
Labels: DWOC, Level-3

#201 Created POST route for adding admins
  backend/app/routes/admin/index.js
  backend/app/routes/admin/postAdmin.js
  backend/app/routes/auth/login.js
  backend/package-lock.json
Labels: Level-4, SWOC, backend

#246 [Bug] Fix the buttons for small screens #235
  frontend/src/components/util/button/button.css
Labels: DWOC, Level-3

#250 Made the title and text centre aligned in mobile view in home page
  frontend/src/components/home/overview/overview.css
Labels: DWOC, Level-3

#252 Fixing our motive section
  frontend/src/components/home/motive/motive.css
  frontend/src/components/home/motive/motive.js
Labels: Level-3, SWOC

#243 Make admin page UI #222
  frontend/src/app.js
  frontend/src/components/Admin_Dashboard/admin-dashboard.css
  frontend/src/components/Admin_Dashboard/admin-dashboard.js
  frontend/src/components/navbar/navbar.js
Labels: Level-4, SWOC

#244 issue #94
  backend/app/routes/admin/@validationSchema/index.js
  backend/app/routes/admin/changePassword.js
  backend/app/routes/admin/index.js
Labels: Level-5, SWOC

#261 Enhanced the footer
  frontend/src/app.js
  frontend/src/components/footer/footer.css
Labels: DWOC, Level-3

#264 privacy policy page enhanced for DWoC
  frontend/public/images/privacy.png
  frontend/src/components/privacy-policy/privacy-policy.css
  frontend/src/components/privacy-policy/privacy-policy.js
Labels: DWOC, Level-3

#253 About Us Page Enhanced for DWoC
  frontend/public/images/about-us.jpg
  frontend/public/images/profile.png
  frontend/public/images/team.png
  frontend/src/components/about/about_us.css
  frontend/src/components/about/about_us.js
Labels: DWOC, Level-4

#254 Broadcast update
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.js
  frontend/src/components/broadcast/Carousel/Carousel.js
  frontend/src/components/broadcast/Carousel/Modal/Modals.js
  frontend/src/components/broadcast/broadcast_second.js
  frontend/src/components/broadcast/card.js
  frontend/src/components/broadcast/owl.css
Labels: Level-3, Level-5, SWOC

#275 Adding Resource Sharing UI
  assets/Resource Sharing  (2).png
Labels: DWOC, Level-4, SWOC

#273 did all the required changes in the login page
  frontend/src/components/auth/login/login.css
  frontend/src/components/auth/login/login.js
Labels: Level-3

#282 carousel put inside bootstrap container for DWoC
  frontend/src/components/home/carousel/carousel.js
Labels: DWOC, Level-3

#286 Broadcast mobile view update
  frontend/src/components/broadcast/Carousel/Modal/Modal.css
Labels: Level-3, SWOC

#290 bugs fixed for DWoC
  frontend/public/images/login.png
  frontend/src/components/auth/login/login.js
  frontend/src/components/contact/contact_us.css
  frontend/src/components/resource/resources.css
Labels: DWOC, Level-3

#293 404 page enhanced for DWoC
  frontend/public/images/error.png
  frontend/src/components/404/not_found.css
  frontend/src/components/404/not_found.js
Labels: DWOC, Level-3

#296 Changed the width of active links
  frontend/src/components/navbar/navbar.css
Labels: Level-3

#295 Settings page for Admin #259
  frontend/src/app.js
  frontend/src/components/admin/dashboard/dashboard.js
  frontend/src/components/admin/setting/setting.css
  frontend/src/components/admin/setting/setting.js
Labels: DWOC, Level-4, SWOC

#301 Enhancement in Admin Dashboard
  frontend/public/images/admin.png
  frontend/src/components/admin/dashboard/dashboard.css
  frontend/src/components/admin/dashboard/dashboard.js
Labels: Level-4, SWOC

#305 Hero section changes
  frontend/src/app.css
  frontend/src/components/home/overview/overview.js
Labels: DWOC, Level-3

#302 Broadcasts
  frontend/src/app.js
  frontend/src/components/allbroadcast/allbroadcast.css
  frontend/src/components/allbroadcast/allbroadcasts.js
  frontend/src/components/broadcast/broadcast.css
  frontend/src/components/broadcast/broadcasts.js
Labels: Level-4

#309 [Frontend] All Broadcasts Page #288
  frontend/src/app.js
  frontend/src/components/broadcast/All-broadcast/All-Broadcast.css
  frontend/src/components/broadcast/All-broadcast/All-Broadcast.js
  frontend/src/components/broadcast/broadcasts.js
Labels: DWOC, Level-4, SWOC

#303 New Resource Page
  frontend/src/components/resource/resources.css
  frontend/src/components/resource/resources.js
Labels: Level-3, SWOC

#316 Scroll to top button added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.js
  frontend/src/components/util/scroll-to-top/scrolltop.css
  frontend/src/components/util/scroll-to-top/scrolltop.js
Labels: Level-4, SWOC
