Repository HITK-TECH-Community/Community-Website, pull requests merged in 2022-03, with the labels that each got.

#726 creating an endpoint to save teammember data
  backend/app.js
  backend/app/models/TeamMember.js
  backend/app/routes/index.js
  backend/app/routes/teamMember/addTeam.js
  backend/app/routes/teamMember/index.js
  backend/package.json
Labels: Level3, GSSoC22

#733 Allow admins to get join us requests
  backend/app/routes/index.js
  backend/app/routes/joinUs/get.js
  backend/app/routes/joinUs/index.js
  backend/tests/routes/joinUs/getJoinUs.test.js
Labels: Level2, GSSoC22

#742 Test post join us api
  backend/app/routes/joinUs/@validationSchema/index.js
  backend/tests/routes/joinUs/postJoinUs.test.js
Labels: Level1, GSSoC22

#747 Backend API for uploading resources
  backend/app/models/resource.js
  backend/app/routes/index.js
  backend/app/routes/resources/@validationSchema/index.js
  backend/app/routes/resources/addResource.js
  backend/app/routes/resources/index.js
  backend/tests/routes/resources/postresource.test.js
  backend/utility/emailTemplates.js
Labels: Level3, GSSoC22

#749 [Backend] PATCH/PUT API for updating the upvotes of Question & Answers stored in Db #729
  backend/app/routes/Q&A/answers/downvoteAnswer.js
  backend/app/routes/Q&A/answers/index.js
  backend/app/routes/Q&A/answers/upvoteAnswer.js
  backend/app/routes/Q&A/question/downvoteQuestion.js
  backend/app/routes/Q&A/question/index.js
  backend/app/routes/Q&A/question/upvoteQuestion.js
Labels: Level3, GSSoC22

#757 Resources: Get resources API
  backend/app/routes/resources/getResource.js
  backend/app/routes/resources/index.js
  backend/tests/routes/resources/getresources.test.js
Labels: Level2, GSSoC22

#756 feat(Q&A): Q&A test
  backend/app/routes/Q&A/answers/post.js
  backend/app/routes/Q&A/question/post.js
  backend/tests/routes/Q&A/downvoteAnswer.test.js
  backend/tests/routes/Q&A/downvoteQuestion.test.js
  backend/tests/routes/Q&A/postAnswer.test.js
  backend/tests/routes/Q&A/postQuestion.test.js
  backend/tests/routes/Q&A/upvoteAnswer.test.js
  backend/tests/routes/Q&A/upvoteQuestion.test.js
Labels: Level2, GSSoC22

#755 API route for getting contact us form info
  backend/app/models/contactUs.js
  backend/app/routes/contactUs/@validationSchema/index.js
  backend/app/routes/contactUs/get.js
  backend/app/routes/contactUs/index.js
  backend/app/routes/index.js
  frontend/src/pages/ContactUs/ContactUs.jsx
Labels: Level2, JWOC

#751 Api to delete resource of a given id and delete all resource older than 2months using cron job
  backend/app/routes/resources/deleteResource.js
  backend/app/routes/resources/index.js
  backend/index.js
  backend/tests/routes/resources/deleteresource.test.js
  backend/utility/emailTemplates.js
Labels: Level3, GSSoC22

#744 Responsive-Changes
  frontend/public/index.html
  frontend/src/pages/About/about.module.scss
  frontend/src/pages/Home/components/Carousel/carousel.module.scss
  frontend/src/pages/Home/components/Overview/Overview.jsx
  frontend/src/pages/Home/components/Overview/overview.module.scss
Labels: Level1, GSSoC22

#761 get admin details implemented on endpoint /admin
  backend/app/routes/admin/@validationSchema/index.js
  backend/app/routes/admin/getAdmins.js
Labels: Level1, GSSoC22

#763 commiting the changes in resource page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/Admin/Components/Resource/Resource.jsx
  frontend/src/pages/Admin/Components/Resource/resource.module.scss
Labels: Level3, GSSoC22

#764 Integrating get join us api
  frontend/src/pages/Admin/Components/JoinUs/Card/Card.jsx
  frontend/src/pages/Admin/Components/JoinUs/Card/card.module.scss
  frontend/src/pages/Admin/Components/JoinUs/Card/index.js
  frontend/src/pages/Admin/Components/JoinUs/JoinUs.jsx
  frontend/src/pages/Admin/Components/JoinUs/joinus.module.scss
Labels: Level2, GSSoC22

#745 Enhancement: Add Broadcast Form
  frontend/package-lock.json
  frontend/src/pages/Admin/Components/Broadcast/AddBroadcasts/AddBroadcasts.jsx
  frontend/src/pages/Admin/Components/Broadcast/AddBroadcasts/add-broadcasts.module.scss
Labels: Level2, GSSoC22

#772 [Frontend+Backend] Make the Manage FAQ Page
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Faq/Faq.jsx
  frontend/src/pages/Admin/Components/Faq/ManageFaq/ManageFaq.jsx
  frontend/src/pages/Admin/Components/Faq/ManageFaq/index.js
  frontend/src/pages/Admin/Components/Faq/ManageFaq/manage-faq.module.scss
Labels: Level3, GSSoC22

#779 [Backend] Add API For Deletion
  backend/app/routes/joinUs/deleteJoinUs.js
  backend/app/routes/joinUs/index.js
  backend/app/routes/joinUs/post.js
  backend/app/routes/teamMember/deleteTeamMember.js
  backend/app/routes/teamMember/index.js
  backend/tests/routes/joinUs/deleteJoinUs.test.js
  backend/tests/routes/teamMember/deleteTeamMember.js
  backend/tests/utils/file.png
Labels: Level2, GSSoC22

#780 [Frontend] Integrate delete feature into resource tab
  frontend/src/pages/Admin/Components/Resource/Resource.jsx
Labels: Level2, GSSoC22
