Repository HITK-TECH-Community/Community-Website, pull requests merged in 2024-01, with the labels that each got.

#827 feat: add codeql workflow for javascript
  .github/workflows/codeql.yml
Labels: SWOCS4

#835 adjusted contact-us and join-us pages css
  frontend/src/pages/Admin/Components/Contact/Card/card.module.scss
  frontend/src/pages/Admin/Components/Contact/contactus.module.scss
  frontend/src/pages/Admin/Components/JoinUs/joinus.module.scss
  frontend/src/pages/Admin/admin.module.scss
Labels: Level0, Swoc

#832 fix: remove console log messages on theme change
  frontend/src/app.js
  frontend/src/components/util/ScrollToTop/ScrollToTop.jsx
Labels: Level0, Swoc, SWOCS4
