Repository HITK-TECH-Community/Community-Website, pull requests merged in 2024-05, with the labels that each got.

#864 [Frontend] Join US Enhancements #790
  frontend/.env
  frontend/src/pages/Admin/Components/JoinUs/Card/Card.jsx
  frontend/src/pages/Admin/Components/JoinUs/Card/card.module.scss
  frontend/src/pages/Admin/Components/JoinUs/JoinUs.jsx
Labels: level2, gssoc

#867 dashboard route bug fix issue #830
  frontend/src/app.js
Labels: level1, gssoc

#868 [Frontend] Integrate Get Team on Admin Panel Fixed
  frontend/package-lock.json
  frontend/public/images/defaultUser.png
  frontend/src/pages/Admin/Components/MangeTeams/ManageTeams.jsx
  frontend/src/pages/Admin/Components/MangeTeams/manage-teams.module.scss
Labels: level2, gssoc

#880 fixed the select domain button for light theme
  frontend/src/pages/Home/components/JoinUsForm/Form.jsx
  frontend/src/pages/Home/components/JoinUsForm/form.module.scss
Labels: level1, gssoc

#876 [Bug] Fix backend addteammembers api is Fixed
  backend/app/routes/faq/updateFaq.js
  backend/app/routes/joinUs/deleteJoinUs.js
  backend/app/routes/teamMember/addTeam.js
  backend/app/routes/teamMember/deleteTeamMember.js
Labels: level1, gssoc

#884 Correcting req.body of GetAdmins api #883
  backend/app/routes/admin/@validationSchema/index.js
  backend/app/routes/admin/getAdmins.js
Labels: level1, gssoc

#882 Integrate GET Questions in Frontend
  frontend/src/pages/Q&A/Q&A.jsx
  frontend/src/pages/Q&A/Ques.scss
Labels: level3, gssoc

#891 [Frontend] Integrate Add Team Member API with Frontend Fixed
  frontend/src/pages/Admin/Components/About/About.jsx
  frontend/src/pages/Admin/Components/AddTeamMember/AddTeamMember.jsx
Labels: level3, gssoc

#898 submit button in Q&A page corrected
  frontend/src/pages/Q&A/Q&A.jsx
  frontend/src/pages/Q&A/Ques.scss
Labels: level1, gssoc

#902 getAdmin api integrated with profile page issue#767
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Profile/Profile.jsx
  frontend/src/store/actions/auth.js
Labels: level2, gssoc

#908 added the styles for dropdown which fixed the look
  frontend/src/pages/Admin/Components/AddTeamMember/add-team-member.module.scss
Labels: level1, gssoc

#901 [Frontend] Add Q&A section in admin panel
  backend/app/routes/Q&A/answers/index.js
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Faq/Faq.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/ManageQ&A.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/index.js
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/manage.module.scss
  frontend/src/pages/Admin/Components/Faq/Q&A/QandA.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/index.js
  frontend/src/pages/Admin/Components/Faq/Q&A/qanda.module.scss
Labels: level3, gssoc

#910 Added instruction for nvm for easier installation.
  README.md
Labels: level1, gssoc

#914 [Frontend] Integrate the Delete Team Member API with frontend Fixed
  backend/app/routes/teamMember/index.js
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/ManageQ&A.jsx
  frontend/src/pages/Admin/Components/MangeTeams/ManageTeams.jsx
  frontend/src/pages/Admin/Components/MangeTeams/manage-teams.module.scss
Labels: level3, gssoc

#918 getAdmin api updated to send id also
  backend/app/routes/admin/getAdmins.js
Labels: backend, level1

#920 [Backend] Add Delete API for Questions and Answers Fixed
  backend/app/routes/Q&A/answers/deleteAnswer.js
  backend/app/routes/Q&A/answers/index.js
  backend/app/routes/Q&A/question/deleteQuestion.js
  backend/app/routes/Q&A/question/index.js
Labels: level3, gssoc

#925 changed "ask your question ui"
  frontend/src/pages/Q&A/Q&A.jsx
  frontend/src/pages/Q&A/Ques.scss
  frontend/src/pages/Resources/components/ResourceSharingForm/ResourceSharingForm.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/resource-sharing-form.module.scss
Labels: level1, gssoc

#924 [Frontend] Integrate delete for Questions and Answers in admin Fixed
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/ManageQ&A.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/manage.module.scss
  frontend/src/pages/Admin/Components/Faq/Q&A/qanda.module.scss
Labels: level3, gssoc

#926 [Backend] Delete Api for contactUs details created
  backend/app/routes/contactUs/delete.js
  backend/app/routes/contactUs/index.js
  backend/app/routes/index.js
Labels: level2, gssoc

#929 Updated joinUS section background-color
  frontend/src/pages/Home/components/JoinUs/join-us.module.scss
Labels: level1, gssoc

#930 [Backend] The DELETE teamMemebers API should also delete the respective file stored in the disk Fixed
  backend/app/routes/teamMember/deleteTeamMember.js
Labels: level2, gssoc

#934 [Frontend] Integrate Delete Contact Us API Fixed
  frontend/src/pages/Admin/Components/Contact/Card/Card.jsx
  frontend/src/pages/Admin/Components/Contact/Contact.jsx
Labels: level2, gssoc

#942 [Backend] Limiting the Number of upvotes/downvotes a particular user can do Fixed
  backend/app.js
  backend/app/routes/Q&A/question/downvoteQuestion.js
  backend/app/routes/Q&A/question/index.js
  backend/app/routes/Q&A/question/upvoteQuestion.js
  backend/helpers/middlewares/cookie.js
  backend/package.json
  frontend/.env
Labels: level3, gssoc

#931 update functionality for Admin profile
  backend/app/models/Admin.js
  backend/app/routes/admin/getAdmins.js
  backend/app/routes/admin/index.js
  backend/app/routes/admin/updateAdmin.js
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Profile/Profile.jsx
  frontend/src/pages/Admin/Components/Profile/profile.module.scss
  frontend/src/pages/Admin/admin.module.scss
Labels: level3, gssoc

#940 [Resource Sharing Form] fixed alignment of the input fields in the form
  frontend/src/pages/Resources/components/ResourceSharingForm/resource-sharing-form.module.scss
Labels: level1, gssoc

#956 [Frontend] The Broadcast isn't appearing in correct format Fixed
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Card/Card.jsx
  frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
  frontend/src/pages/Broadcast/Component/Carousel/Modal/Modals.jsx
Labels: level2, gssoc

#951 Refactoring dashboard contact us component
  frontend/src/pages/Admin/Components/Contact/Card/card.module.scss
  frontend/src/pages/Admin/Components/Contact/Contact.jsx
Labels: level1, gssoc

#963 [Backend] Auth remove for post contact us Fixed
  backend/app/routes/contactUs/get.js
  backend/app/routes/contactUs/index.js
Labels: level2, gssoc

#969 deleteAdmin Api fix issue #952
  backend/app/routes/faq/deleteFaq.js
  backend/app/routes/faq/index.js
  backend/app/routes/index.js
  frontend/src/pages/Admin/Components/Faq/AddFaq/AddFaq.jsx
  frontend/src/pages/Admin/Components/Faq/ManageFaq/ManageFaq.jsx
  frontend/src/pages/Faq/Faq.jsx
Labels: level3, gssoc

#973 Integrated Delete Faq with Backend #679
  frontend/src/pages/Admin/Components/Faq/Faq.jsx
  frontend/src/pages/Admin/Components/Faq/ManageFaq/ManageFaq.jsx
Labels: level2, gssoc

#970 [Fixed bugs] Refactor AddFaq page replace react-tag-input
  frontend/src/pages/Admin/Components/Faq/AddFaq/AddFaq.jsx
  frontend/src/pages/Admin/Components/Faq/AddFaq/add-faq.module.scss
Labels: level2, gssoc

#972 [Frontend] Integrated the Get Team API With Frontend Fixed
  frontend/public/images/founder.jpeg
  frontend/src/pages/About/About.jsx
Labels: level3, gssoc

#980 [Refactor] Frontend API Calls should be kept under the Service folder for contact us Fixed
  frontend/src/common/constants.js
  frontend/src/pages/Admin/Components/Contact/Contact.jsx
  frontend/src/pages/ContactUs/ContactUs.jsx
  frontend/src/service/ContactUs.jsx
Labels: level2, gssoc

#983 updateFaq functionality and Integrate it with Backend
  frontend/src/pages/Admin/Components/Faq/ManageFaq/ManageFaq.jsx
  frontend/src/pages/Admin/Components/Faq/ManageFaq/manage-faq.module.scss
Labels: level2, gssoc
