Repository HITK-TECH-Community/Community-Website, pull requests merged in 2024-06, with the labels that each got.

#1009 [Refactor] Frontend API Calls should be kept under the Service folder for Broadcast Fixed
  frontend/src/pages/Admin/Components/Broadcast/AddBroadcasts/AddBroadcasts.jsx
  frontend/src/pages/Admin/Components/Broadcast/ManageBroadcasts/Card/Card.jsx
  frontend/src/pages/Admin/Components/Broadcast/ManageBroadcasts/ManageBroadcasts.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/AllBroadcasts.jsx
  frontend/src/pages/Broadcast/Component/Carousel/Carousel.jsx
  frontend/src/service/Broadcast.jsx
Labels: level2, gssoc

#992 [Refactor] Frontend API Calls should be kept under the Service folder for about
  frontend/src/pages/About/About.jsx
  frontend/src/pages/Admin/Components/AddTeamMember/AddTeamMember.jsx
  frontend/src/pages/Admin/Components/MangeTeams/ManageTeams.jsx
  frontend/src/service/About.jsx
Labels: level2, gssoc

#996 [Refactor] Frontend API Calls should be kept under the Service folder for Resources Fixed
  frontend/src/pages/Admin/Components/Resource/Resource.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/ResourceSharingForm.jsx
  frontend/src/service/Resources.jsx
Labels: level2, gssoc

#1003 [Refactor] Frontend API Calls should be kept under the Service folder for Faq Fixed
  frontend/src/pages/Admin/Components/Faq/AddFaq/AddFaq.jsx
  frontend/src/pages/Admin/Components/Faq/ManageFaq/ManageFaq.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/ManageQ&A.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/QandA.jsx
  frontend/src/pages/Faq/Faq.jsx
  frontend/src/pages/Q&A/Q&A.jsx
  frontend/src/service/Faq.jsx
  frontend/src/service/toastService.jsx
Labels: level2, gssoc

#994 Responsiveness fixed for medium screen
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Dashboard/Dashboard.jsx
  frontend/src/pages/Admin/Components/Dashboard/dashboard.module.scss
  frontend/src/pages/Admin/admin.module.scss
Labels: level1, gssoc

#1017 Add hover effects for admin menu options
  frontend/src/pages/Admin/admin.module.scss
Labels: level1, gssoc

#1019 Fixed Button text is out of alignment on mobile view
  frontend/src/components/ErrorHandlerPages/LoggedIn/LoggedIn.jsx
Labels: gssoc

#1023 Fixed tags should not contains spaces
  frontend/src/components/util/Tags.jsx
  frontend/src/pages/Admin/Components/Broadcast/AddBroadcasts/AddBroadcasts.jsx
  frontend/src/pages/Admin/Components/Faq/AddFaq/AddFaq.jsx
Labels: level1, gssoc

#1032 Added Testimonials - Frontend
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/components/Testimonials/Testimonials.jsx
  frontend/src/pages/Home/components/Testimonials/index.js
  frontend/src/pages/Home/components/Testimonials/testimonial.module.scss
  frontend/src/pages/Home/components/Testimonials/testimonials.js
Labels: level2, gssoc

#1031 Refactor Resource Form: Create new broadcast upon successful resource form submission
  backend/app/models/Broadcast.js
  backend/app/models/resource.js
  backend/app/routes/resources/@validationSchema/index.js
  backend/app/routes/resources/addResource.js
  backend/app/routes/resources/deleteResource.js
  backend/app/routes/resources/getResource.js
  backend/app/routes/resources/index.js
  backend/app/routes/resources/postResource.js
  backend/index.js
  frontend/src/common/constants.js
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Dashboard/Dashboard.jsx
  frontend/src/pages/Admin/Components/Resource/Resource.jsx
  frontend/src/pages/Admin/Components/Resource/index.js
  frontend/src/pages/Admin/Components/Resource/resource.module.scss
  frontend/src/pages/Resources/components/ResourceSharingForm/ResourceSharingForm.jsx
  frontend/src/pages/Resources/components/ResourceSharingForm/resource-sharing-form.module.scss
  frontend/src/service/Resources.jsx
Labels: level3, gssoc

#1035 [ Backend ]Create Get Testimonial API
  backend/app/models/Testimonial.js
  backend/app/routes/index.js
  backend/app/routes/testimonial/getTestimonials.js
  backend/app/routes/testimonial/index.js
Labels: level2, gssoc

#1041 [Frontend] Integrate Get Testimonials API with frontend fixed
  frontend/src/pages/Home/components/Testimonials/Testimonials.jsx
  frontend/src/pages/Home/components/Testimonials/testimonial.module.scss
  frontend/src/pages/Home/components/Testimonials/testimonials.js
  frontend/src/service/Testimonial.jsx
Labels: level2, gssoc

#1043 [Backend] Create POST Testimonial API
  backend/app/routes/testimonial/@validationSchema/index.js
  backend/app/routes/testimonial/index.js
  backend/app/routes/testimonial/postTestimonial.js
Labels: level2, gssoc

#1044 [Backend] Create DELETE Testimonial API
  backend/app/routes/testimonial/deleteTestimonial.js
  backend/app/routes/testimonial/index.js
Labels: level2, gssoc

#1046 fix(Q&A): input fields getting cleared and autoclosing the box pop after submission
  frontend/src/pages/Q&A/Q&A.jsx
Labels: level1, gssoc

#1053 [Frontend] Manage/Add Testimonial on Admin Panel Added
  frontend/public/images/testimonialImg.png
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Dashboard/Dashboard.jsx
  frontend/src/pages/Admin/Components/Testimonial/AddTestimonial/AddTestimonial.jsx
  frontend/src/pages/Admin/Components/Testimonial/AddTestimonial/add-testimonial.module.scss
  frontend/src/pages/Admin/Components/Testimonial/AddTestimonial/index.js
  frontend/src/pages/Admin/Components/Testimonial/ManageTestimonial/ManageTestimonial.jsx
  frontend/src/pages/Admin/Components/Testimonial/ManageTestimonial/index.js
  frontend/src/pages/Admin/Components/Testimonial/ManageTestimonial/manage-testimonial.module.scss
  frontend/src/pages/Admin/Components/Testimonial/Testimonial.jsx
  frontend/src/pages/Admin/Components/Testimonial/index.js
  frontend/src/pages/Admin/Components/Testimonial/testimonial.module.scss
  frontend/src/service/Testimonial.jsx
Labels: level3, gssoc

#1056 [BUG] post testimonials backend Fixed
  backend/app/models/Testimonial.js
  backend/app/routes/testimonial/index.js
  backend/app/routes/testimonial/postTestimonial.js
  frontend/src/pages/Admin/Components/Testimonial/AddTestimonial/AddTestimonial.jsx
  frontend/src/pages/Admin/Components/Testimonial/ManageTestimonial/ManageTestimonial.jsx
  frontend/src/service/Testimonial.jsx
Labels: level2, gssoc

#1047 Admin profile validation
  frontend/src/pages/Admin/Components/Profile/Profile.jsx
Labels: level1, gssoc

#1061 Fix Update Broadcast Modal Description Population and Refactor form for Styling Consistency
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Broadcast/ManageBroadcasts/ManageBroadcasts.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Edit/Edit.jsx
  frontend/src/pages/Broadcast/Component/AllBroadcasts/Edit/edit.module.scss
Labels: level1, gssoc
