Repository HITK-TECH-Community/Community-Website, pull requests merged in 2024-08, with the labels that each got.

#1101 Bug Fixed: Question tags are not getting saved correctly.
  frontend/src/pages/Q&A/Q&A.jsx
Labels: level1, gssoc

#1104 UI to answer the questions in Q&A Section Added
  frontend/src/pages/Q&A/AnswerModel/AnswerModel.jsx
  frontend/src/pages/Q&A/AnswerModel/AnswerModel.scss
  frontend/src/pages/Q&A/AnswerModel/index.js
  frontend/src/pages/Q&A/Q&A.jsx
  frontend/src/pages/Q&A/Ques.scss
  frontend/src/service/Faq.jsx
Labels: level2, gssoc

#1106 Answers integrated into Q&A page
  frontend/src/pages/Q&A/AnswerModel/AnswerModel.jsx
  frontend/src/pages/Q&A/AnswerModel/AnswerModel.scss
Labels: level2, gssoc

#1105 [Frontend] Improve the Manage Q&A UI
  frontend/src/pages/Admin/Admin.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/ManageQ&A.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/index.js
  frontend/src/pages/Admin/Components/Faq/Q&A/ManageQ&A/manage.module.scss
  frontend/src/pages/Admin/Components/Faq/Q&A/QandA.jsx
  frontend/src/pages/Admin/Components/Faq/Q&A/qanda.module.scss
Labels: level2, gssoc

#1111 FrontEnd: upvote/downvote for Answers in Q&A page Integrated
  frontend/src/pages/Q&A/AnswerModel/AnswerModel.jsx
  frontend/src/pages/Q&A/AnswerModel/AnswerModel.scss
  frontend/src/pages/Q&A/Q&A.jsx
  frontend/src/pages/Q&A/Ques.scss
  frontend/src/service/Faq.jsx
Labels: level3, gssoc

#1110 Backend : Upvote and Downvote for Answers Fixed
  backend/app/models/answers.js
  backend/app/models/question.js
  backend/app/routes/Q&A/answers/downvoteAnswer.js
  backend/app/routes/Q&A/answers/index.js
  backend/app/routes/Q&A/answers/upvoteAnswer.js
  backend/app/routes/Q&A/question/@validationSchema/index.js
Labels: level2, gssoc

#1118 Backend: Add Subscribers for Newsletter
  backend/app/models/Subscriber.js
  backend/app/routes/index.js
  backend/app/routes/subscribers/@validationSchema/index.js
  backend/app/routes/subscribers/index.js
  backend/app/routes/subscribers/postSubscriber.js
Labels: level3, gssoc

#1117 Integration Join Us Form with backend
  frontend/src/pages/Home/components/JoinUsForm/Form.jsx
  frontend/src/pages/Home/components/JoinUsForm/form.module.scss
  frontend/src/service/JoinUs.jsx
Labels: level2, gssoc

#1119 Email Signup Submission Fixed
  frontend/src/components/Footer/Footer.jsx
  frontend/src/service/Subscriber.jsx
Labels: level1, gssoc

#1121 Backend: Welcome email for New Subscribers added
  backend/app/routes/subscribers/postSubscriber.js
  backend/utility/emailTemplates.js
Labels: level2, gssoc

#1123 Adding Team Member fixed
  frontend/src/pages/Admin/Components/AddTeamMember/AddTeamMember.jsx
  frontend/src/service/About.jsx
Labels: level2, gssoc

#1126 Social media icon in footer fixed
  frontend/src/components/Footer/footer.module.scss
Labels: level1, gssoc

#1129 Feature : Keep me logged In feature added
  backend/app/models/Admin.js
  backend/app/routes/admin/changePassword.js
  backend/app/routes/admin/getAdmins.js
  backend/app/routes/admin/resetPassword.js
  backend/app/routes/auth/@validationSchema/index.js
  backend/app/routes/auth/login.js
  backend/helpers/middlewares/auth.js
  frontend/src/pages/Admin/Components/Setting/ResetPassword/ResetPassword.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Login/login.module.scss
Labels: level3, gssoc
